# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking
# See: https://nikitabobko.github.io/AeroSpace/guide

after-login-command = []
after-startup-command = []
start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30 # 30
default-root-container-layout = 'accordion'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = true

exec-on-workspace-change = ['/bin/bash', '-c',
'exec-and-forget borders active_color=0xffed6b5f inactive_color=0xff494d64 width=5.0 style=round'
]

[[on-window-detected]]
if.app-name-regex-substring = "finder"
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = "arq"
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = "passwords"
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = "devon"
run = 'layout floating'

[[on-window-detected]]
if.app-id="com.mitchellh.ghostty"
run= [
  "layout floating",
]

# Possible values: (qwerty|dvorak)
[key-mapping]
preset = 'qwerty'
# [key-mapping.key-notation-to-key-code]
# q = 'q'
# w = 'w'
# f = 'e'
# p = 'r'
# g = 't'
# j = 'y'
# l = 'u'
# u = 'i'
# y = 'o'
# semicolon = 'p'
# leftSquareBracket = 'leftSquareBracket'
# rightSquareBracket = 'rightSquareBracket'
# backslash = 'backslash'

# a = 'a'
# r = 's'
# s = 'd'
# t = 'f'
# d = 'g'
# h = 'h'
# n = 'j'
# e = 'k'
# i = 'l'
# o = 'semicolon'
# quote = 'quote'

# z = 'z'
# x = 'x'
# c = 'c'
# v = 'v'
# b = 'b'
# k = 'n'
# m = 'm'
# comma = 'comma'
# period = 'period'
# slash = 'slash'

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        5
outer.right =      5

[mode.main.binding]

ctrl-alt-f = '''exec-and-forget osascript -e '
tell application "Finder" to activate'
'''
ctrl-alt-enter = 'exec-and-forget open -a /apps/Applications/Ghostty.app'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
ctrl-alt-slash = 'layout tiles horizontal vertical' # period
ctrl-alt-comma = 'layout accordion horizontal vertical' # m

# colemak: hjkl --> hnei
ctrl-alt-h = 'focus left'
ctrl-alt-n = 'focus down'
ctrl-alt-e = 'focus up'
ctrl-alt-i = 'focus right'

ctrl-alt-shift-h = 'move left'
ctrl-alt-shift-n = 'move down'
ctrl-alt-shift-e = 'move up'
ctrl-alt-shift-i = 'move right'

ctrl-alt-w = 'close'

ctrl-alt-shift-minus = 'resize smart -50'
ctrl-alt-shift-equal = 'resize smart +50'

ctrl-alt-1 = 'workspace 1'
ctrl-alt-2 = 'workspace 2'
ctrl-alt-3 = 'workspace 3'
ctrl-alt-4 = 'workspace 4'
ctrl-alt-5 = 'workspace 5'

ctrl-alt-shift-1 = 'move-node-to-workspace 1'
ctrl-alt-shift-2 = 'move-node-to-workspace 2'
ctrl-alt-shift-3 = 'move-node-to-workspace 3'
ctrl-alt-shift-4 = 'move-node-to-workspace 4'
ctrl-alt-shift-5 = 'move-node-to-workspace 5'

ctrl-alt-tab = 'workspace-back-and-forth'

ctrl-alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

ctrl-alt-shift-o = 'mode service'
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # p reset layout
f = ['layout floating tiling', 'mode main'] # t Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

# sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
#s = ['layout sticky tiling', 'mode main']

ctrl-alt-shift-h = ['join-with left', 'mode main']
ctrl-alt-shift-n = ['join-with down', 'mode main']
ctrl-alt-shift-e = ['join-with up', 'mode main']
ctrl-alt-shift-i = ['join-with right', 'mode main']

down = 'volume down'
up = 'volume up'
shift-down = ['volume set 0', 'mode main']
