
# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    kernelPackages = pkgs.linuxKernel.packages.linux_rpi4;
    initrd.availableKernelModules = [ "xhci_pci" "usbhid" "usb_storage" ];
    loader = {
      grub.enable = false;
    #  generic-extlinux-compatible.enable = true;
    #
  # from old machines/rpi.nix
  # Use the extlinux boot loader. (NixOS wants to enable GRUB by default)
  # Enables the generation of /boot/extlinux/extlinux.conf
      generic-extlinux-compatible.enable = false;
      raspberryPi.enable = true;
# Set the version depending on your raspberry pi. 
      raspberryPi.version = 4;
    #  raspberryPi.firmwareConfig = ''
    #    dtparam=audio=on
    #    dtoverlay=dwc2
    #  '';
    };

  # initrd.kernelModules = [ ];
  # kernelModules = [ ];
  # extraModulePackages = [ ];

  };

  swapDevices = [ ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
