#!/usr/bin/env sh

# necessary to load scripting-addition during startup on macOS Big Sur
# *yabai --load-sa* is configured to run through sudo without a password
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          6
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config --space 1 layout             float
yabai -m config --space 4 layout             stack
yabai -m config top_padding                  8
yabai -m config bottom_padding               8
yabai -m config left_padding                 8
yabai -m config right_padding                8
yabai -m config window_gap                   8

# do not manages these application
yabai -m rule --add app="^Activity Monitor$"    manage=off
yabai -m rule --add app="^Bitwarden"            manage=off
yabai -m rule --add app="^Capture One"          manage=off
yabai -m rule --add app="^Deliveries$"          manage=off
yabai -m rule --add app="^DEVONthink 3$"        manage=off
yabai -m rule --add app="^Disk Utility$"        manage=off
yabai -m rule --add app="^Finder$"              manage=off
yabai -m rule --add app="^Image Capture$"       manage=off
yabai -m rule --add app="^Karabiner-Elements$"  manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off
yabai -m rule --add app="^Reminders$"           manage=off
yabai -m rule --add app="^QMK Toolbox$"         manage=off
yabai -m rule --add app="^System Preferences$"  manage=off
yabai -m rule --add app="^zoom.us$"             manage=off

# float settings windows
yabai -m rule --add title='Settings$'           manage=off
yabai -m rule --add title='Preferences$'        manage=off
yabai -m rule --add title='Passwords$'          manage=off
# float system preferences
yabai -m rule --add app="^System Information$"  manage=off
yabai -m rule --add app="^System Preferences$"  manage=off

# refresh my Übersicht bar when the space changes
yabai -m signal --add event=space_changed \
    action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"spaces-widget\"'"

# make sure the limelight binary is added somewhere in your $PATH
# kill any existing limelight process if one exists, before we launch a new one
killall limelight &> /dev/null
~/bin/limelight --config ~/.config/limelight/limelightrc &> /dev/null &

echo "yabai configuration loaded.."

