[
#      "adobe-acrobat-reader"
       "airbuddy"
     #  "alfred"
     #  "arc"
     # "arq"
       "backuploupe"
       "balenaetcher"
     # "bartender"
       "bitwarden"
       "bluos-controller"
     #  "brave-browser"
       "calibre"
#      "chatgpt"
       "devonthink"
       "fantastical"
       "firefox"
       "folx"
       "ghostty"
       "grammarly-desktop"
       "houdahspot"
       "iina"
       "itsycal"
       "karabiner-elements"
     #  "kicad"
       "kobo"
       "launchcontrol"
     #  "ltspice"
#      "mactex"
       "marked"
       "mattermost"
       "menubarx"
       "menuwhere"
       "musescore"
       "nikitabobko/tap/aerospace"
      # "notchnook"
       "omnigraffle"
       "onyx"
       "pdf-expert"
       "plex"
       "popclip"
#      "qmk-toolbox"
       "qobuz"
      # "quicksilver"
#      "quiet-reader"
       "raindropio"
       "roon"
       "superduper"
       "switchresx"
       "tailscale"
       "tidal"
       "ukelele"
     # "visual-studio-code"
       "vlc"
       "wezterm"
       "xquartz"
       #"eaglefiler"
       #"font-comic-mono"
       #"font-iosevka-nerd-font"
       #"font-jetbrains-mono"
       #"font-lekton-nerd-font"
       #"font-monaspace"
       #"forehead"
       #"luna-display"
       #"luna-secondary"
       #"lyn"
       #"openzfs"
       #"private-internet-access"
       #"vinegar"
       #"vivid"
     ]
