[
#      "adobe-acrobat-reader"
       "airbuddy"
       "alt-tab"
     # "alfred"
     # "arc"
     # "arq"
       "backuploupe"
       "balenaetcher"
     # "bartender"
       "bitwarden"
       "blackhole-2ch"
       "bloom"
       "bluos-controller"
     # "brave-browser"
       "calibre"
       "claude"
#      "chatgpt"
       "devonthink"
       "discord"
####   "fantastical"
       "firefox"
       "folx"
       "ghostty"
       "grammarly-desktop"
       "grandperspective"
       "google-chrome"
       "hamed-elfayome/claude-usage/claude-usage-tracker"
       "hookmark"
       "houdahspot"
       "iina"
       "itsycal"
       "karabiner-elements"
       "keycastr"
     #  "kicad"
       "kitty"
       "kobo"
       "launchcontrol"
       "leader-key"
     #  "ltspice"
     #  "mactex"
       "marked-app"
       "mattermost"
       "mediathekview"
       "menubarx"
       "menuwhere"
       "musescore"
       "nikitabobko/tap/aerospace"
     # "notchnook"
       "obsidian"
       "omnigraffle"
       "onyx"
       "opera"
       "orion"
       "pdf-expert"
       "plex"
       "popclip"
#      "qmk-toolbox"
     # "qobuz"
     # "quicksilver"
#      "quiet-reader"
       "raindropio"
       "raycast"
       "roon"
       "rustdesk"
       "slack"
       "superduper"
       "switchresx"
     # "tailscale"
       "tidal"
       "ukelele"
     # "visual-studio-code"
       "vlc"
     # "wezterm"
       "xld"
       "xquartz"
       "zoom"
       #"eaglefiler"
       #"font-comic-mono"
       #"font-iosevka-nerd-font"
       #"font-jetbrains-mono"
       #"font-lekton-nerd-font"
       #"font-monaspace"
       #"forehead"
       #"luna-display"
       #"luna-secondary"
       #"lyn"
       #"openzfs"
       #"private-internet-access"
       #"vinegar"
       #"vivid"
     ]
