#!/usr/bin/env sh

# necessary to load scripting-addition during startup on macOS Big Sur
# *yabai --load-sa* is configured to run through sudo without a password
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             first_child    \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               on             \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 on             \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               alt            \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            stack          \


# do not manages these application
# yabai -m rule --add title='Settings$'           manage=off
# yabai -m rule --add title='Preferences$'        manage=off
# yabai -m rule --add title='Passwords$'          manage=off
#
# yabai -m rule --add app="^Finder$"              manage=on
yabai -m rule --add app="^News"                 manage=off
yabai -m rule --add app="^Reeder"               manage=on
yabai -m rule --add app="^Safari"               manage=on

systemApp='^(System Preferences|System Settings|System Information|Finder|Calendar|Contacts|Disk Utility|Image Capture|Notes|Reminders|App Store|Activity Monitor|Dictionary)$'
manageOffApp='^(AnyConnect|Bitwarden|Karabiner-Elements|Karabiner-EventViewer|QMK Toolbox|zoom.us)$'

yabai -m rule --add app="${systemApp}|${manageOffApp}" manage=off

yabai -m signal --add event=window_created \
  action='yabai -m query --windows --window $YABAI_WINDOW_ID \
  | jq -er ".\"can-resize\" or .\"is-floating\"" || \
  yabai -m window $YABAI_WINDOW_ID --toggle float' \
  app!="${systemApp}|${manageOffApp}"

echo "yabai configuration loaded " $(date)
