#!/usr/bin/env sh

# necessary to load scripting-addition during startup on macOS Big Sur
# *yabai --load-sa* is configured to run through sudo without a password
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             first_child    \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               alt            \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# do not manages these application
yabai -m rule --add app="^Activity Monitor$"    manage=off
yabai -m rule --add app="^Bitwarden$"           manage=off
yabai -m rule --add app="^Capture One"          manage=off
yabai -m rule --add app="^Contacts$"            manage=off
yabai -m rule --add app="^Deliveries$"          manage=off
yabai -m rule --add app="^DEVONthink 3$"        manage=off
yabai -m rule --add app="^Disk Utility$"        manage=off
yabai -m rule --add app="^Finder$"              manage=off
yabai -m rule --add app="^Image Capture$"       manage=off
yabai -m rule --add app="^Karabiner-Elements$"  manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off
yabai -m rule --add app="^QMK Toolbox$"         manage=off
yabai -m rule --add app="^Reminders$"           manage=off
yabai -m rule --add app="^System Preferences$"  manage=off
yabai -m rule --add app="^zoom.us$"             manage=on
yabai -m rule --add app="^System Information$"  manage=off
yabai -m rule --add app="^System Settings$"     manage=off
yabai -m rule --add title='Settings$'           manage=off
yabai -m rule --add title='Preferences$'        manage=off
yabai -m rule --add title='Passwords$'          manage=off

echo "yabai configuration loaded.."

